### ISSUE TITLE
rake assets:precompile fails with 5.0.3

### ISSUE THREAD

**Issue by gucki** [rails/sass-rails#336]
When upgrading sass-rails from 4.x to 5.0.3 rake assets:precompile no longer works. It seems it just stops somewhere in the middle, no error is shown. This happens both server-side on deployment and even locally when testing assets precompilation. Looking at the public/assets folder I don't see any "manifest-_.json" file, only a ".sprockets-manifest-_.json" file exists. Reverting sass-rails back to 4.0.5 makes precompilation work again. The project is using rails 4.2.2.

**Comment by Fudoshiki** [comment]
sass-rails (6.0.0)
same issue

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by Fudoshiki** [comment]
https://github.com/Fudoshiki/example-precompile

**Comment by Fudoshiki** [comment]
also
Rails.application.config.assets.precompile << [/\.(css|js)\z/] in assets.rb raise error now

NoMethodError: undefined method `start_with?' for /\.(css|js)\z/:Regexp

**Comment by bolandrm** [comment]
@Fudoshiki did you remove the example app?
