### ISSUE TITLE
sass-rails-5.0.4 does not work with sprockets-4.0.0.beta2 (pulled in via sprockets-rails-3.0.4)

### ISSUE THREAD

**Issue by kikonen** [rails/sass-rails#372]
```
.../gems/sass-rails-5.0.4/lib/sass/rails/railtie.rb:57:in `block (2 levels) in <class:Railtie>': undefined method `register_engine' for #<Sprockets::Environment:0x007fef447d9958> (NoMethodError)
Did you mean?  register_pipeline
	from .../gems/sprockets-rails-3.0.4/lib/sprockets/railtie.rb:144:in `block in build_environment'
	from .../gems/sprockets-rails-3.0.4/lib/sprockets/railtie.rb:143:in `each'
	from .../gems/sprockets-rails-3.0.4/lib/sprockets/railtie.rb:143:in `build_environment'
	from .../gems/railties-4.2.6/lib/rails/railtie.rb:194:in `public_send'
```

**Comment by kikonen** [comment]
Actually it seems that this was due to sprockets (4.0.0.beta2).

**Comment by rafaelfranca** [comment]
the only version of sass-rails that support sprockets 4 is sass-rails 6.
